### PR TITLE
ormolu suggestion

### PR DESCRIPTION
**Pull request by tonyday567**
This is the big, ugly one. Will let you contemplate on whether ormolu is a thing we should do.

### CODE REVIEW

**Comment by santiweight** [comment]
Oof there is one I don't like about this one which is the removal of multiline haddocks. I went with Kowainik's recommendation to purposefully use multiline haddocks - was that you or ormolu who did that?

**Comment by santiweight** [comment]
On the other hand, I have quickly realised that I don't really have an opinion about whether we use multiline or regular haddocks! if you have a preference I will happily go with that.

**Comment by santiweight** [comment]
That PatternSynonyms thing is pretty weird huh. I'm guessing that ormolu is not using the local cabal file but is instead just parsing each file independently. Perhaps PatternSynonyms has some special treatment in the parser?

**Comment by santiweight** [comment]
This comment https://github.com/tweag/ormolu/issues/633#issuecomment-652241855

appears to have a fix. It looks like you need to pass `-o -XPatternSynonyms` to ormolu in order to pattern synonyms to work. Should be easy enough. I'd be happy to add a scripts folder if you want to make this job easier to run.

**Comment by santiweight** [comment]
Or according to the ormolu readme, you may be able to use `--cabal-default-extensions` to get things to work if there is a local cabal file.

**Comment by tonyday567** [comment]
I hate it, the multi-line conversion, which is all ormolu. But it comes as the default with haskell-language-server, maximising potential collaborators, and has no configuration to ever argue about, so we will never find ourselves wasting time of formating differences.

**Comment by santiweight** [comment]
I agree, ormolu is a resounding winner then. Let's go ormolu.

**Pull request merged**
